default: &default
  adapter: postgresql
  encoding: utf8
  database: blog_development
  username: postgres
  password: root

development:
  adapter: postgresql
  encoding: utf8
  database: blog_development
  username: postgres
  password: root