default: &default
   adapter: postgresql
   encoding: utf8
   database: sales_development
   username: postgres
   password: root

development:
  adapter: postgresql
  encoding: utf8
  database: sales_development
  username: postgres
  password: root